### DISCUSSION TITLE
2024.32 impact on TeslaUSB

### DISCUSSION THREAD

**Discussion by KrzysztofHajdamowicz** [marcone/teslausb#885] [General]
https://www.notateslaapp.com/news/2287/tesla-disables-12v-power-sockets-and-usb-ports-while-sentry-mode-is-active-in-update-202432

Looks like Sentry Mode no longer provides power to USB ports.
Maybe they are woken up when recording have to be dumped.

**Comment by marcone** [comment]
It's not clear from that article whether this applies to the USB port that has the USB drive in it. One person on the TeslaUSB Discord commented that they're on 2024.32.10, and their glovebox USB remains powered while Sentry is active.

**Reply by marcone** [reply]
So after doing some investigation today, I found that USB remains powered while Sentry is on, but it appears that TeslaUSB can no longer use the Tesla API to turn on Sentry mode, so you would have to do that manually using the Tesla app. Camp mode is an option too, but probably uses more power than Sentry mode since it turns on climate control.

**Reply by mrd0n** [reply]
A potential path if current options elude implementation:    

I've been using this https://github.com/yoziru/esphome-tesla-ble on an esp32 D1 mini to control charging my car when extra solar is available over Bluetooth BLE instead of using the old/new api.  It works very reliably. 

In addition to controlling charging, it also has an "awake" car service built in.   

The option could be to keep the car awake using this with an ESP32 or if raspberry PI's have BLE capability, developing BLE control into TeslaUSB.

**Reply by marcone** [reply]
Does that "awake" option actually wake up the car enough to power up the USB ports?

**Reply by mrd0n** [reply]
I've confirmed that waking the car via BLE is no different than waking the car other ways (e.g. via the app or via the API) and it does not enable the USB port.   But... 

I have a solution working via an ESP device over BLE!  

Here's what is working:
- enable the teslausb notification Webhook option to trigger a webhook automation in home assistant (HA)
- Within the HA webhook trigger, if the POSTed data contains "including"   (TeslaUSB sends teslsusb: Archiving XX file(s) **including**..., then turn on the Sentry switch which sends the command over BLE from the esp32 device
- - Within the HA webhook trigger, if the POSTed data contains "completed"   (TeslaUSB sends teslsusb: Archiving **completed**..., then turn off the Sentry switch which sends the command over BLE from the esp32 device

If anyone has teslausb, home assistant with the ESPHome add-on and a spare ESP32, and would like to try this, I will get this documented.

**Reply by marcone** [reply]
> I've confirmed that waking the car via BLE is no different than waking the car other ways (e.g. via the app or via the API) and it does not enable the USB port. But...
> 
> I have a solution working via an ESP device over BLE!
> 
> Here's what is working:
> 
> * enable the teslausb notification Webhook option to trigger a webhook automation in home assistant (HA)
> * Within the HA webhook trigger, if the POSTed data contains "including"   (TeslaUSB sends teslsusb: Archiving XX file(s) **including**..., then turn on the Sentry switch which sends the command over BLE from the esp32 device
> * * Within the HA webhook trigger, if the POSTed data contains "completed"   (TeslaUSB sends teslsusb: Archiving **completed**..., then turn off the Sentry switch which sends the command over BLE from the esp32 device
> 
> If anyone has teslausb, home assistant with the ESPHome add-on and a spare ESP32, and would like to try this, I will get this documented.

Is this something that the Pi itself could do? (since Raspberry Pi supposedly supports BLE)

**Reply by mrd0n** [reply]
I would think so.  Here is the foundational library written in C++ called "Tesla Vehicle Command" (formally TeslaBLE ) https://github.com/pmdroid/tesla-vehicle-command    

I have tried to get basic BLE working on my raspberry pi Zero W (my teslausb device) and I think there is a hardware revision issue (some rpi zero W have working BLE and some don't). Or maybe I just didn't try hard enough?  The library is focused on Arduino / esp32 hardware, but the bones are there to try on other hardware.   Because I already use Home Assistant and ESP32's are only $5-10, I went that way.

**Reply by mrd0n** [reply]
I should have mentioned that my experience controlling a Tesla over BLE is way more responsive (literally sub 2 seconds) versus using the old API which seemed to take 5-10 seconds.

**Reply by herrfrei** [reply]
@mrd0n I'm also trying to use an ESP32 to switch sentry mode on / off via HA, but only if it wasn't previously enabled. Since I don't want to have the BLE key device in the car (security concerns), I use MQTT from teslausb to send the sentry on / off command (the only one allowed for the MQTT user). But this requires to add awake / asleep scripts (I use Python for that). My question is: How can I enable the teslausb notification webhook and consume it in HA?

**Reply by marcone** [reply]
TeslaUSB supports multiple push notification methods for notifying when archiving starts and stops. One of those is a generic webhook, so you could just configure that with the appropriate URL for Home Assistant.

**Reply by mrd0n** [reply]
This exactly...

Here is my home assistant webhook configuration:

```
- id: '1731910368590'
  alias: Webhook - louie - teslausb
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: -e5P3v2RhCFjaoBanBH7mzU3w
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ ''including'' in trigger.json.value2 }}'
      sequence:
      - action: notify.mobile_app_iphone_don
        metadata: {}
        data:
          message: 'Louie teslausb: Sentry On'
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.tesla_ble_68d2a4_sentry_switch
    - conditions:
      - condition: template
        value_template: '{{ ''completed'' in trigger.json.value2 }}'
      sequence:
      - action: notify.mobile_app_iphone_don
        metadata: {}
        data:
          message: 'Louie teslausb: Sentry Off'
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.tesla_ble_68d2a4_sentry_switch
  mode: single
```

This is triggered by teslausb notification by this within teslausb_setup_variables.conf:
```
# Uncomment if setting up Webhook notifications
export WEBHOOK_ENABLED=true
export WEBHOOK_URL=http://172.16.1.111:8123/api/webhook/-e5P3v2RhCFjaoBanBH7mzU3w
```
It's working flawlessly for me.   (Louie is the name of my car)

It should be straightforward in the home assistant automation to add the logic to only turn on Sentry if it's not already on, while storing the previous Sentry state in a helper variable so that you also know to turn Sentry off or not when the video transfer is complete..

**Reply by herrfrei** [reply]
I see, thanks for the tip with the webhook! I've been using HA for a couple years, but never stumbled across it. You don't need a helper variable to save the previous Sentry state - the ESPhome device entity stores the state (on = triggered manually). So, my actions look like this:

```yaml
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'including' in trigger.json.value2 }}"
          - condition: not
            conditions:
              - condition: state
                entity_id: binary_sensor.tesla_sentry_mode
                state: "on"
        sequence:
          - action: notify.matrix_notify
            data:
              message: Sentry mode activated from TeslaUSB
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.tesla_ble_ce9d28_sentry_switch
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ 'completed' in trigger.json.value2 }}"
          - condition: state
            entity_id: switch.tesla_ble_ce9d28_sentry_switch
            state: "on"
        sequence:
          - action: notify.matrix_notify
            data:
              message: Sentry mode deactivated from TeslaUSB
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.tesla_ble_ce9d28_sentry_switch
```
